[project]
name = 'openEMS'
version = '0.0.36'
description = "Python interface for the openEMS FDTD library"
classifiers = [
	'Development Status :: 3 - Alpha',
	'Intended Audience :: Developers',
	'Intended Audience :: Information Technology',
	'Intended Audience :: Science/Research',
	'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
	'Programming Language :: Python',
	'Programming Language :: Python :: 3',
	'Programming Language :: Python :: 3.9',
	'Programming Language :: Python :: 3.10',
	'Programming Language :: Python :: 3.11',
	'Programming Language :: Python :: 3.12',
	'Programming Language :: Python :: Implementation :: CPython',
	'Topic :: Scientific/Engineering',
	'Topic :: Software Development :: Libraries :: Python Modules',
	'Operating System :: POSIX :: Linux',
	'Operating System :: Microsoft :: Windows',
]
authors = [
	{name = 'Thorsten Liebig', email = 'Thorsten.Liebig@gmx.de'}
]
maintainers = [
	{name = 'Thorsten Liebig', email = 'Thorsten.Liebig@gmx.de'}
]
dependencies = [
	'numpy',
	'h5py',
	'CSXCAD',
]

[project.urls]
Documentation = 'https://openEMS.de'
Source = 'https://github.com/thliebig/CSXCAD/tree/master/python'

[build-system]
requires = ['setuptools','Cython']
build-backend = 'setuptools.build_meta'
